version: '3.1'
services:
  minio:
    image: minio/minio:RELEASE.2023-07-07T07-13-57Z
    ports:
      - 9000:9000
      - 9001:9001
    environment:
       MINIO_ROOT_USER: BURHAN
       MINIO_ROOT_PASSWORD: BURHAN-PASS
    command: server --console-address ":9001" /data


